### ISSUE TITLE
connecting or disconnecting a listener while handling an emit

### ISSUE THREAD

**Issue by nealeyoung** [erdewit/eventkit#12]
What is the expected behavior of the following?

```
from eventkit import Event

event = Event("event")


def hello():
    global event
    print("hello")
    event += goodbye        # Changing the order of this line 
    event -= hello          # and the next changes the output.

def goodbye():
    print("goodbye")


event += hello

event.emit()
event.emit()
```

Per the comment above, changing the order of those two lines unexpectedly changes the output.   It looks to me that while the first emit() is in the middle of iterating over the event slots (line 190, see [2] below), disconnecting a listener (as in `event -= hello`) causes all the slots to be rebuilt (line 157, see [1] below).  Will this lead to undefined behavior?  It seemed to be giving me unexpected results in more complicated situations.

Perhaps the emit for loop (line 190) should make a copy of the slots before iterating over them?

[1] https://github.com/erdewit/eventkit/blob/8fb52fef0eb8137f8ea0af9cca59d300beff0e7d/eventkit/event.py#L157

[2] https://github.com/erdewit/eventkit/blob/8fb52fef0eb8137f8ea0af9cca59d300beff0e7d/eventkit/event.py#L190

**Comment by erdewit** [comment]
The ``goodbye`` handler is added while the event is emitting, and is then called during this same emit. I agree that this is not what is expected.

> Perhaps the emit for loop (line 190) should make a copy of the slots before iterating over them?

Indeed, that looks like an excellent way to fix this.
