### ISSUE TITLE
Potential issue if an event handler disconnects itself during event handling

### ISSUE THREAD

**Issue by sohailsomani** [erdewit/eventkit#2]
https://github.com/erdewit/eventkit/blob/b7f424ed18a650d25fc3bd2b032280bdb4d42381/eventkit/event.py#L175

This would modify the `self._slots` array which I believe is a no-no. Making a copy of `self._slots` would probably be sufficient. This is purely on a code-review, I have not tested it.

**Comment by erdewit** [comment]
Thank you for reviewing the code. The copy is made in ``disconnect``, were the removed slot is also deactivated:

```python
    def disconnect(self, listener, error=None, done=None):
        obj, func = self._split(listener)
        for slot in self._slots:
            if (slot[0] is obj or slot[1] and slot[1]() is obj) \
                    and slot[2] is func:
                slot[0] = slot[1] = slot[2] = None
                break
        self._slots = [s for s in self._slots if s != [None, None, None]]
        ...
```

So the iteration in ``emit`` will then proceed with the older copy of ``self._slots``, with the disconnected slot blanked out.

**Comment by sohailsomani** [comment]
You genius. How did I miss that, sorry for the noise!
