### ISSUE TITLE
Event.aiter could be optimized for skip_to_last=True case

### ISSUE THREAD

**Issue by rgeronimi** [erdewit/eventkit#3]
Event.aiter allows a skip_to_last boolean argument that, when set to True, only yields last values from the source event, skipping intermediate values since the previous yield.

The current implementation uses an asynchronous queue for the entire method, whatever the value of the skip_to_last boolean argument.
https://github.com/erdewit/eventkit/blob/71b4c60d5af41e8c366c00f09c4a7b5c228444ee/eventkit/event.py#L322

However when skip_to_last=True, it is not necessary anymore to use a queue: simple state variables remembering the last state of the source iterator are sufficient.

This could vastly reduce the memory consumption for intensive source events emitting many values - which is exactly the optimization case skip_to_last=True was intended for.

**Comment by dmoklaf** [comment]
As a side (very minor) comment, the current implementation also uses 3-state string values (None, "ERROR", "DONE") to track special states. This could be done with 3-state boolean values instead, which are intended exactly for that case (None, False, True - the boolean meaning is whether the streaming was successfully completed or erroneously completed).
