### ISSUE TITLE
crash upon simple import within PyCharm under Debug

### ISSUE THREAD

**Issue by markusmaresch** [erdewit/eventkit#4]
I came across this trying to use/debug ib-insync, but really believe it is some strange interaction of eventkit, asyncio and PyCharm, which I can not explain nor solve. Could be a PyCharm issue, could be an asyncio issue.
Can't debug ib-insync really ...

Any help is appreciated. Maybe user error ...

create an environment with at least **eventkit** and **numpy**.
create 2 liner:
```
echo "import eventkit; print(eventkit.__version__)" > ev.py 
```

Works:
python ev.py
result: 0.8.9

Open PyCharm (I have Community Edition 2021.2.3 on OsX)
connect to the correct environment
Run: works: result 0.8.9

Debug: crash upon "import eventkit" with exception within exception 
[eventkit_pycharm_debug_crash.txt](https://github.com/erdewit/eventkit/files/7493025/eventkit_pycharm_debug_crash.txt)
..

**Comment by erdewit** [comment]
It seems asyncio crashes when setting up the so called self-pipe. It works for me in PyCharm.

You can try if this crashes as well:
```python
import asyncio
loop = asyncio.get_event_loop()
```

**Comment by markusmaresch** [comment]
Yes, asyncio example crashes as well. Will push it down streams. Thanks! Consider closing issue here.

**Comment by markusmaresch** [comment]
Seems to be a PyCharm issue
