### ISSUE TITLE
pytest simulate event

### ISSUE THREAD

**Issue by wojoeraf** [erdewit/eventkit#5]
Hi,

Is there a way to simulate the happening of an event in a unit test?
Background: I'm using ib_insync and trying to write unit tests for functions which use the waitOnUpdate() method.

Sorry if the answer is maybe obvious, but I haven't found out how.

Thanks

**Comment by erdewit** [comment]
An event can be fired with it's ``emit`` method with the events' arguments, if any.

For example like ``ib.updateEvent.emit()``.
