### ISSUE TITLE
datetime.timedelta does not seem to be handled

### ISSUE THREAD

**Issue by WladimirOstrovsky** [erdewit/eventkit#8]
Hi, 

I was developing an application which should trigger every k minutes. For developing reasons I was using the following codesnippet which worked fine.

`from datetime import datetime, timedelta`

`timer_check = eventkit.Timerange(start=datetime.now(), step=20)
``timer_check += _on_timer_check
`

As soon as I change to 
`timer_check = eventkit.Timerange(start=datetime.now(), step=timedelta(seconds=20))
`
the code runs, but no event is triggered anymore, which is I believe something is not working properly. 

Would be great to receive a feedback.

**Comment by erdewit** [comment]
Thanks for the bug report. This is fixed in v1.0.1
