### ISSUE TITLE
.map is lost bc of using weak refs

### ISSUE THREAD

**Issue by rafalkrupinski** [erdewit/eventkit#9]
I'm simply setting up a pipeline in a function:
```python
def test():
    def _setup(ev: Event, target: Callable):
        ev2 = ev.map(lambda x: x * 2)
        ev2 += target

    async def atest():
        ev = Event()
        _setup(ev, print)
        print('start')
        ev.emit(1)
        ev.emit(2)

    import asyncio
    asyncio.get_event_loop().run_until_complete(atest())
    # asyncio.run(atest())
```

I'm expecting to see 2 and 4 printed but I only get 'start'.
It looks like the ev2 is lost as soon as the _setup is left, because keep_ref is False by default (and using += gives no way to change it).

So for this to work correctly I'd need to keep a reference to every single transformer in the pipeline, or I'd need to explicitly create and connect Map objects with keep_ref=True, right?

Is using weak refs by default a good idea?

**Comment by erdewit** [comment]
Use ``event.connect(..., keep_ref=True``) to keep a hard reference. This is not the default as it easily leads to memory leaks.

**Comment by rafalkrupinski** [comment]
OK. I'm just curious how could it lead to memory leak. I mean, why wouldn't you want to keep those listeners working?

**Comment by rafalkrupinski** [comment]
> Use `event.connect(..., keep_ref=True`) to keep a hard reference. This is not the default as it easily leads to memory leaks.

So you're suggesting something like this:
```python
    def setup(ev: Event, target: Callable):
        ev3 = eventkit.Map(lambda x: x + 1)
        ev4 = eventkit.Map(lambda x: x * 2)
        ev3.connect(ev4, keep_ref=True)
        ev2 = ev.connect(ev3, keep_ref=True)
        ev.connect(ev2, keep_ref=True)
        ev4+=target
```

**Comment by erdewit** [comment]
I think you're right about keeping hard refs when pipe-lining these operators. I will look into this.

**Comment by rafalkrupinski** [comment]
Cool.

I looked a bit through the code and I see operator classes keep source (hard) ref, in order to disconnect themselves on `done` event.

Why not just release downstream refs from within source?
Simplified code:
```
def set_done():
  while self._slots:
    slot = self._slots.pop()
    slot.set_done()
```

Why not keep only downstream refs?

**Comment by erdewit** [comment]
The ``_source`` serves as a hard ref to prevent the source from being garbage-collected when the operator is not done yet.

> Why not just release downstream refs from within source?

The source does not know when the the operator is done. Often the operator is done when the source is done, but not always: The ``Delay`` operator for example. So the decision of when the operator is done has to be made by the operator itself.
